spring.application.name=adminBackendUE
# Puerto del servidor (opcional, pero asegura que corra en el 8080)
server.port=8080

# Configuración de la Base de Datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/udlaeats_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate (Crea las tablas automáticamente)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect